# Generated by Django 5.2.10 on 2026-01-13 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_action_id_alter_position_id_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subjects',
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='Назва класу')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Опис класу')),
                ('subjects', models.ManyToManyField(blank=True, default=None, null=True, to='Profile.subject', verbose_name='Список предметів')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='class_room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.classroom'),
        ),
    ]
